-- begin SERVICE4VEHICLES_CLIENT
create unique index IDX_SERVICE4VEHICLES_CLIENT_UK_PHONE_NUMBER on SERVICE4VEHICLES_CLIENT (PHONE_NUMBER) where DELETE_TS is null ^
-- end SERVICE4VEHICLES_CLIENT
-- begin SERVICE4VEHICLES_ORDER
alter table SERVICE4VEHICLES_ORDER add constraint FK_SERVICE4VEHICLES_ORDER_ON_ADDRESS foreign key (ADDRESS_ID) references SERVICE_FOR_VEHICLES(ID)^
alter table SERVICE4VEHICLES_ORDER add constraint FK_SERVICE4VEHICLES_ORDER_ON_CLIENT foreign key (CLIENT_ID) references SERVICE4VEHICLES_CLIENT(ID)^
alter table SERVICE4VEHICLES_ORDER add constraint FK_SERVICE4VEHICLES_ORDER_ON_SERVICE foreign key (SERVICE_ID) references SERVICE4VEHICLES_SERVICE(ID)^
create index IDX_SERVICE4VEHICLES_ORDER_ON_ADDRESS on SERVICE4VEHICLES_ORDER (ADDRESS_ID)^
create index IDX_SERVICE4VEHICLES_ORDER_ON_CLIENT on SERVICE4VEHICLES_ORDER (CLIENT_ID)^
create index IDX_SERVICE4VEHICLES_ORDER_ON_SERVICE on SERVICE4VEHICLES_ORDER (SERVICE_ID)^
-- end SERVICE4VEHICLES_ORDER
